sudo: false
language: generic

# Speed builds up by caching install requirements
cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - lua5.1
      - liblua5.1-0
      - liblua5.1-0-dev
      - ghc-8.0.2
    sources:
      - hvr-ghc

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
# Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - ulimit -n 4096
  - stack --no-terminal --install-ghc build
script:
  - stack exec lua-version
  - stack exec callbacks
  - stack exec haskellfun
  - stack exec err_prop
  - (cd examples/lualib_in_haskell && make clean && make && LD_LIBRARY_PATH=. lua main.lua)
